package com.educollab.model;

public enum ProjectActivityEventType {
  PROJECT_CREATED,
  PROJECT_VISIT,
  MILESTONE_CREATED,
  MILESTONE_COMPLETED,
  TASK_CREATED,
  TASK_STATUS_CHANGED,
  TASK_COMPLETED,
  DISCUSSION_POST_CREATED,
  DISCUSSION_REPLY_CREATED,
  DOCUMENT_CREATED,
  DOCUMENT_VERSION_SAVED,
  FILE_UPLOADED,
  ASSIGNMENT_SUBMITTED,
  GIT_COMMIT_PUSHED
}
